# Generated by Django 3.2.16 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название фильма')),
                ('name', models.TextField(verbose_name='Имя покупателя')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор билета')),
                ('time', models.DateTimeField(verbose_name='Время и дата сеанса')),
                ('hall', models.IntegerField(verbose_name='Номер зала')),
                ('ending', models.DateField(verbose_name='Конец показа')),
                ('price', models.IntegerField(verbose_name='Цена билета')),
                ('count', models.IntegerField(verbose_name='Кличество билетов')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('title',),
            },
        ),
    ]
