# Generated by Django 3.2.16 on 2025-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ('number',), 'verbose_name': 'зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.RemoveField(
            model_name='hall',
            name='count',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='ending',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='time',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='title',
        ),
        migrations.AddField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(default=1, verbose_name='Количество мест в зале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='count_rows',
            field=models.IntegerField(default=1, verbose_name='Количество рядов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='number',
            field=models.IntegerField(choices=[(1, 'Thunder Arena'), (2, 'Classic Premium'), (3, 'Starlight Hall'), (4, 'Romance Lounge'), (5, 'Silver Screen'), (6, 'Vision Max'), (7, 'Mega Action')], default=1, unique=True, verbose_name='Номер зала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор зала'),
        ),
    ]
