# Generated by Django 3.2.16 on 2025-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена билета'),
            preserve_default=False,
        ),
    ]
