# Generated by Django 3.2.16 on 2025-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_hall_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(default=100, verbose_name='Количество мест в зале'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='count_rows',
            field=models.IntegerField(default=10, verbose_name='Количество рядов'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price',
            field=models.IntegerField(default=500, verbose_name='Цена билета'),
        ),
    ]
