# Generated by Django 3.2.16 on 2025-11-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20251120_1530'),
        ('admin_panel', '0005_auto_20251120_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сеанса')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Фильм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('date', 'start_time'),
                'unique_together': {('hall', 'date', 'start_time')},
            },
        ),
    ]
