# Generated by Django 3.2.16 on 2025-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(default=10, verbose_name='Количество мест в зале'),
        ),
    ]
