# Generated by Django 3.2.16 on 2025-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_hall_count_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(default=10, verbose_name='Количество мест в ряду'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер зала'),
        ),
    ]
