# Generated by Django 3.2.16 on 2025-11-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название фильма')),
                ('name', models.CharField(max_length=256, verbose_name='Имя покупателя')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Номер билета')),
                ('time', models.DateTimeField(verbose_name='Время и дата сеанса')),
                ('hall', models.CharField(max_length=256, verbose_name='Название зала')),
                ('price', models.IntegerField(verbose_name='Цена билета')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('place', models.IntegerField(verbose_name='Место')),
                ('session_id', models.IntegerField(verbose_name='ID сеанса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(verbose_name='ID сеанса')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('place', models.IntegerField(verbose_name='Место')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier_panel.order')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'Брони',
                'unique_together': {('session_id', 'row', 'place')},
            },
        ),
    ]
