# Generated by Django 3.2.16 on 2025-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_panel', '0002_auto_20251121_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя покупателя'),
        ),
    ]
