# Generated by Django 3.2.16 on 2025-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('time', models.TimeField(verbose_name='Длительность фильма')),
                ('beginning', models.DateField(verbose_name='Начало показа')),
                ('ending', models.DateField(verbose_name='Конец показа')),
                ('price', models.IntegerField(verbose_name='Цена билета')),
                ('age_limit', models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Возрастное ограничение')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Афиша')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('title',),
            },
        ),
    ]
