# Generated by Django 3.2.16 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default=1, max_length=256, verbose_name='Страна происхождения'),
            preserve_default=False,
        ),
    ]
