# Generated by Django 3.2.16 on 2025-11-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='price',
        ),
    ]
