# Generated by Django 3.2.16 on 2025-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена билета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Номер билета'),
        ),
    ]
