# Generated by Django 3.2.16 on 2025-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20251120_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='price',
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Номер фильма'),
        ),
    ]
